### ISSUE TITLE
[PATCH] polkit-0.115 fails to build on POSIX platforms (like Linux/musl) due to requiring netgroup support

### ISSUE THREAD

**Issue by polkit-github-migration-bot** [polkit-org/polkit#15]
In gitlab.freedesktop.org by bugzilla-migration on May 20, 2012, 08:31

Link to the original issue: https://gitlab.freedesktop.org/polkit/polkit/-/issues/14
## Submitted by Natanael Copa  
Assigned to **David Zeuthen `@david`**  

**[Link to original bug (#50145)](https://bugs.freedesktop.org/show_bug.cgi?id=50145)**  
## Description
Fails to build with the error:
  CCLD   polkitd
../../src/polkitbackend/.libs/libpolkit-backend-1.so: undefined reference to `setnetgrent'
../../src/polkitbackend/.libs/libpolkit-backend-1.so: undefined reference to `innetgr'
../../src/polkitbackend/.libs/libpolkit-backend-1.so: undefined reference to `getnetgrent'
../../src/polkitbackend/.libs/libpolkit-backend-1.so: undefined reference to `endnetgrent'
collect2: ld returned 1 exit status
make[1]: *** [polkitd] Error 1
make[1]: Leaving directory `/home/ncopa/aports/main/polkit/src/polkit-0.105/src/polkitd'

The problem is that netgroup (introduced with 674357c20c1b6cb421fea6eb6924b274ec477c0e) is not defined in POSIX and therefore not implemented in uclibc. The netgroup support should be a compiletime option.

Please note that it is during linking that the error happens so the configure script could check for getnetgrent linking.

related bug: #43610

### See also
  * https://bugs.gentoo.org/show_bug.cgi?id=561672

**Comment by polkit-github-migration-bot** [comment]
In gitlab.freedesktop.org by bugzilla-migration on May 20, 2012, 08:47

:hammer_and_wrench: **Natanael Copa** submitted a patch:
>>>
This quick-and-dirty patch makes it compile and should work. You might want add an --disable-netgroups configure option or similar.
>>>
  
  
~~**Patch 61878**~~, "Quick and dirty fix":  
[0001-Bug-50145-make-netgroup-support-optional.patch](https://gitlab.freedesktop.org/polkit/polkit/uploads/a04dd86298f9970fbb37cbc6e16068b6/0001-Bug-50145-make-netgroup-support-optional.patch)

**Comment by polkit-github-migration-bot** [comment]
In gitlab.freedesktop.org by bugzilla-migration on Jan 31, 2013, 15:38

:hammer_and_wrench: **Natanael Copa** submitted a patch:
>>>
Updated version of the patch.
>>>
  
  
~~**Patch 73996**~~, "make netgroup support optional":  
[0001-Bug-50145-make-netgroup-support-optional.patch](https://gitlab.freedesktop.org/polkit/polkit/uploads/dd09e7d95cf6eb1cd237f7f06cbc9bdf/0001-Bug-50145-make-netgroup-support-optional.patch)

**Comment by polkit-github-migration-bot** [comment]
In gitlab.freedesktop.org by bugzilla-migration on Oct 8, 2015, 09:52

:hammer_and_wrench: **René Rhéaume** submitted a patch:
>>>
It also does not work as is with version 0.113 on Lilblue (Gentoo using uclibc as system libc). My patch is a little different from the Natanel's one.
>>>
  
  
~~**Patch 118753**~~, "make netgroup support optional for version 0.113":  
[polkit-0.113-optional-netgroup-r2.patch](https://gitlab.freedesktop.org/polkit/polkit/uploads/dd940191987821d3ac5680bc7a72c0af/polkit-0.113-optional-netgroup-r2.patch)

**Comment by polkit-github-migration-bot** [comment]
In gitlab.freedesktop.org by bugzilla-migration on Oct 9, 2015, 12:25

:speech_balloon: **Miloslav Trmac** said:
>>>
Thanks for the patch.

1. If a system administrator does configure the system to use netgroups, polkit should somehow visibly refuse the configuration instead of silently ignoring it.  Sadly polkit_unix_netgroup_new() cannot fail, so it might mean tracking down the callers and how they are used.  (Then, get_user_in_net_group/js_polkit_user_is_in_netgroup could perhaps be #ifdef-ed to g_assert_not_reached()}.

2. Code-wise, it would be nice to minimize the number of ifdefs/conditions in the code. I guess that would mean having #ifdefs only inside get_users_in_net_group and js_polkit_user_is_in_netgroup instead of removing the functions entirely and then needing more ifdefs in their callers.


Sadly I don’t have _that_ much time for polkit and supporting non-glibc systems is honestly quite low on the priority list; still, 1. above does need to be dealt with before shipping support in an upstream release.
>>>

**Comment by polkit-github-migration-bot** [comment]
In gitlab.freedesktop.org by bugzilla-migration on Jul 11, 2018, 12:49

:hammer_and_wrench: **A. Wilcox** submitted a patch:
>>>
This patch has been written entirely from scratch by me from the latest Git master.

It takes all of the advice from the last patch's review:

- Show an error if configuration includes 'unix-netgroup:'.
- Put g_assert_not_reached in polkit_unix_netgroup_new since all callers have been modified to error out before it is reached.
- Pass all tests on a glibc/x86_64 machine and a musl/ppc64 machine.
>>>
  
  
~~**Patch 140555**~~, "Make Netgroup support optional":  
[0001-make-netgroup-support-optional.patch](https://gitlab.freedesktop.org/polkit/polkit/uploads/f11bff0d08f270594e86e57bcf4aa7f4/0001-make-netgroup-support-optional.patch)

**Comment by polkit-github-migration-bot** [comment]
In gitlab.freedesktop.org by bugzilla-migration on Jul 11, 2018, 12:51

:hammer_and_wrench: **A. Wilcox** submitted a patch:
>>>
And this one foregoes adding itself as a new file in the root source tree... whoops.  Sorry about that.
>>>
  
  
**Patch 140556**, "Make Netgroup support optional":  
[0001-make-netgroup-support-optional.patch](https://gitlab.freedesktop.org/polkit/polkit/uploads/55095aa51a42eb80e53f5dda969f4aab/0001-make-netgroup-support-optional.patch)

**Comment by polkit-github-migration-bot** [comment]
In gitlab.freedesktop.org by awilfox on Nov 27, 2018, 16:59

mentioned in commit awilfox/polkit@864968c357effa01304095b8c96d2e094a0cb984

**Comment by polkit-github-migration-bot** [comment]
In gitlab.freedesktop.org by awilfox on May 1, 2019, 17:14

mentioned in commit awilfox/polkit@778bb45e0e0cbabe2b04adf67a500af1dab09768
